# Generated by Django 5.2.5 on 2025-08-24 05:49

import server.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SatelliteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='City / major place (e.g. New Delhi)', max_length=120)),
                ('sublocation', models.CharField(blank=True, help_text='Optional finer location (e.g. north)', max_length=120, null=True)),
                ('image', models.ImageField(upload_to=server.models.satellite_image_upload_to)),
                ('captured_at', models.DateTimeField(blank=True, help_text='When the satellite captured the image', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
